services:
  airflow:
    build: .
    command: standalone
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/airflow/dags
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USER:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD:-admin}
    volumes:
      - ./airflow:/opt/airflow/airflow
      - ./src:/opt/airflow/src
      - ./dbt:/opt/airflow/dbt
      - ./data:/opt/airflow/data
      - ./tests:/opt/airflow/tests
    ports:
      - "8080:8080"

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      - airflow
