version: 2

models:
  - name: gold_clima_uf_mensal
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [uf, ano, mes]
    columns:
      - name: n_estacoes
        data_tests:
          - dbt_utils.accepted_range:
              min_value: 1
      - name: precipitacao
        data_tests:
          - dbt_utils.accepted_range:
              min_value: 0

  - name: gold_safra_uf
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [uf, cultura, ano]
    columns:
      - name: uf
        data_tests:
          - relationships:
              to: ref('dim_uf')
              field: uf
      - name: cultura
        data_tests:
          - relationships:
              to: ref('dim_cultura')
              field: cultura

  - name: gold_clima_safra
    columns:
      - name: rendimento
        data_tests:
          - dbt_utils.accepted_range:
              min_value: 0
              severity: warn
